# Generated by Django 5.2.6 on 2025-10-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('tasks', '0005_alter_task_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                (
                    'tag',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tag_tasks',
                        to='tags.tag',
                    ),
                ),
                (
                    'task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='task_tags',
                        to='tasks.task',
                    ),
                ),
            ],
            options={
                'db_table': 'task_tags',
                'unique_together': {('task', 'tag')},
            },
        ),
    ]
