# Generated by Django 5.2.6 on 2025-09-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktag',
            old_name='tag',
            new_name='tags',
        ),
    ]
