# Generated by Django 5.2.6 on 2025-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_tags", "0002_rename_tag_tasktag_tags"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tasktag",
            table="task_tags",
        ),
    ]
