# Generated by Django 5.2.6 on 2025-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_tags", "0003_alter_tasktag_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tasktag",
            table=None,
        ),
    ]
