# Generated by Django 5.2.6 on 2025-10-09 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('NEW', 'New'),
                            ('IN_PROGRESS', 'In Progress'),
                            ('COMPLETED', 'Completed'),
                        ],
                        default='NEW',
                        max_length=11,
                    ),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[
                            ('LOW', 'Low'),
                            ('MEDIUM', 'Medium'),
                            ('HIGH', 'High'),
                        ],
                        default='MEDIUM',
                        max_length=10,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'assigned',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='owner_tasks',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['status', 'priority', 'due_date'],
                        name='tasks_task_status_668b02_idx',
                    )
                ],
            },
        ),
    ]
