# Generated by Django 5.2.6 on 2025-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_assigned"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_status_d1d175_idx",
            old_name="tasks_task_status_668b02_idx",
        ),
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
    ]
