# Generated by Django 5.2.6 on 2025-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks",
            "0003_rename_tasks_task_status_668b02_idx_tasks_status_d1d175_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_task_status_668b02_idx",
            old_name="tasks_status_d1d175_idx",
        ),
        migrations.AlterModelTable(
            name="task",
            table=None,
        ),
    ]
