# Generated by Django 5.2.6 on 2025-10-09 09:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'constraints': [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower('name'),
                        name='unique_tag_name',
                    )
                ],
            },
        ),
    ]
