# Generated by Django 5.2.6 on 2025-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("task_tags", "0003_alter_tasktag_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tags",
        ),
        migrations.AlterModelTable(
            name="tags",
            table="tags",
        ),
    ]
