# Generated by Django 5.2.6 on 2025-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_rename_tag_tags_alter_tags_table"),
        ("task_tags", "0004_alter_tasktag_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
        migrations.AlterModelTable(
            name="tag",
            table=None,
        ),
    ]
