services:

  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: poetry run python manage.py runserver_plus 0.0.0.0:8000
    ports:
      - "8008:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ..:/app:cached

volumes:
  postgres_data:
