# Generated by Django 5.2.6 on 2025-09-26 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        (
            "tasks",
            "0003_rename_tasks_task_status_668b02_idx_tasks_status_d1d175_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
        migrations.AlterModelTable(
            name="comments",
            table="Comments",
        ),
    ]
