# Generated by Django 5.2.6 on 2025-09-30 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_rename_comment_comments_alter_comments_table"),
        (
            "tasks",
            "0004_rename_tasks_status_d1d175_idx_tasks_task_status_668b02_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.AlterModelTable(
            name="comment",
            table=None,
        ),
    ]
