# Generated by Django 5.2.6 on 2025-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
